### PR TITLE
[TS] LPS-100616 Skype small icon in user Contact is broken

### PR DESCRIPTION
**Pull request by katienesterovich**
https://issues.liferay.com/browse/LPS-100616

Previous implementation relied on a discontinued `mystatus` link to return a Skype status-icon. There were two usages - in User Contacts (from LPS ticket) and in Portal Directory widget. There is currently no replacement for the Skype icon in https://issues.liferay.com/browse/LPS-95502 sheet, so I opted to remove it. Additionally, I changed the href syntax used to open Skype (same as used in Loop) since previous implementation did not work.

### CODE REVIEW

**Comment by katienesterovich** [comment]
ci:test:sf

**Comment by katienesterovich** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Finished review. will be forwarded once CI finishes.

**Comment by brianikim** [comment]
https://github.com/SamZiemer/liferay-portal/pull/685

**Pull request closed without merging**
