### PR TITLE
LPS-97585 Index expando field as keyword and make it case insensitive

### PR DESCRIPTION
**Pull request by katienesterovich**
https://issues.liferay.com/browse/LPS-97585

Verified that the fix works and ran source formatter.

Note: to verify, deploy and Reindex all searches indexes in Control Panel > Configuration > Search

### CODE REVIEW

**Comment by katienesterovich** [comment]
ci:test:sf

**Comment by katienesterovich** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
This fix causes regressions. @katienesterovich . I do suggest you return this ticket back to the queue.

Sincerely,
Brian Kim

**Comment by brianikim** [comment]
For more details, please take a look at the test failures specifically for expando on ci:test:relevant

**Pull request closed without merging**
