### PR TITLE
LPS-111915 Unable to preview display page template in draft web content

### PR DESCRIPTION
**Pull request by amandaaakwok**
[LPS-111915](https://issues.liferay.com/browse/LPS-111915)

**Observed Error**: Users are unable to preview the display page template of a web content before the web content is published.

**Root Cause**: To preview the draft web content, the portal fetched the latest _Approved_ version of the article; however, newly created drafts don't have an _Approved_ version yet.

**Solution:** 
`DDMTemplateContentAccessor.getContent()` was modified to pass the JournalArticle as an argument to JournalContentImpl. Before this change, the article to be viewed was fetched by its `groupId` and `articleId` and had a filter of `WorkflowConstants.STATUS_APPROVED` later applied to the query, seen in 
https://github.com/liferay/liferay-portal/blob/7e7782a8cfb106ddfb68231dc8f217633b4a8110/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/internal/util/JournalContentImpl.java#L347-L348
By passing in the JournalArticle, we are able to call `getDisplay()` directly and eliminate the need for the _Approved_ version of the article to be retrieved, allowing the user to view the _Draft_ article.

### CODE REVIEW

**Comment by amandaaakwok** [comment]
ci:test:sf

**Comment by amandaaakwok** [comment]
ci:test:stable

**Comment by amandaaakwok** [comment]
ci:stop

**Comment by brianikim** [comment]
Can you resend this PR after SF changes? Thanks.

**Pull request closed without merging**
