### PR TITLE
[TS] LPS-97294 File removed from Upload field reappears when moving to another field

### PR DESCRIPTION
**Pull request by katienesterovich**
https://issues.liferay.com/browse/LPS-97294

Although state.value was updated to ' ', the field retained the original value. To fix, I added a callback to update field in addition to setting the value to ' '.

Note: see "Fixed" video attached in JIRA to see results.

### CODE REVIEW

**Comment by katienesterovich** [comment]
ci:test:sf

**Comment by katienesterovich** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
These test failures look related. Can you see if they are not reproducible without your fix and reproducible with your fix?

**Comment by brianikim** [comment]
See previous comment

**Pull request closed without merging**
