### PR TITLE
LPS-117316 Fixing NullPointerException when editing content when embedding a portlet with web content

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-117376

The issue here was caused by the the changes made in LPS-106268. The attribute, javax.portlet.request, for the HttpServletRequest object was getting overwritten to null. This caused the porteletRequest object in BaseJournalFormNavigatorEntry -> isEditDefaultValues to be assigned to null when trying to get the javax.portlet.request attribute. Therefore, a NullPointerException was being thrown in ParamUtil -> get when trying to access a parameter of porteletRequest.

To fix the issue, I found that the HttpServletRequest was being stored in the themeDisplay before getting overwritten. I overloaded a few methods to pass the themeDisplay object as a parameter so the portletRequest can be assigned with the correct value stored in the themeDisplay.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Will finish reviewing this on Monday.

**Comment by brianikim** [comment]
As an update, I am still reviewing this. will try to push the PR by tomorrow.

**Comment by brianikim** [comment]
See https://github.com/SamZiemer/liferay-portal/pull/745

**Pull request closed without merging**
