### PR TITLE
LPS-102715 Replace legacy icons in DDM ImageViewer

### PR DESCRIPTION
**Pull request by katienesterovich**
**Ticket**: https://issues.liferay.com/browse/LPS-102715

**Reason**: Purposeful removal of FontAwesome and Glyphicons https://issues.liferay.com/browse/LPS-95502

**Fix**: mimics https://github.com/brianchandotcom/liferay-portal/pull/76557/files from https://issues.liferay.com/browse/LPS-99145

### CODE REVIEW

**Comment by katienesterovich** [comment]
ci:test:relevant

**Comment by katienesterovich** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
Reviewing now.

**Comment by brianikim** [comment]
https://github.com/SamZiemer/liferay-portal/pull/667

**Pull request closed without merging**
