### PR TITLE
LPS-99662 structure setting names allow modification

### PR DESCRIPTION
**Pull request by matthewchan1**
https://issues.liferay.com/browse/LPS-99662

### CODE REVIEW

**Comment by matthewchan1** [comment]
ci:test:relevant

**Comment by matthewchan1** [comment]
ci:test:relevant

**Comment by matthewchan1** [comment]
ci:test:relevant

**Comment by matthewchan1** [comment]
ci:test:sf

**Comment by brianikim** [comment]
Hey @matthewchan1 ,

Could you update the PR with more details? I will redirect the PR once that is completed. Thanks.

**Pull request closed without merging**
