### PR TITLE
LPS-118134 Added file extension to image's temp file name

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-118134

The issue here was occurring because validateModel in JournalArticleModelValidator was creating a temp file name for the featured image attached to the article and when that image was getting validated on allowed file extensions it was returning an error because the file extension was not added to the temp file name.
To fix this bug, I overloaded FileUtil.createTempFile to pass in the featured image's file extension so that the temp file name has the extension added at the end.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @noornajj ,

Please look at the compile error in the test results and fix it.

**Pull request closed without merging**
