### PR TITLE
LPS-98054 staging button should be removed from personal sites

### PR DESCRIPTION
**Pull request by matthewchan1**
https://issues.liferay.com/browse/LPS-98054

Issue:
Staging the personal site causes database constraint violations and cannot be enabled. 

Fix:
After discussing, the staging SME confirmed that Staging for personal sites is not intended, and the solution is to remove it from the menu.

### CODE REVIEW

**Comment by matthewchan1** [comment]
ci:test:relevant

**Comment by matthewchan1** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @matthewchan1 ,

Please investigate the test failure.

Sincerely,
Brian Kim

**Comment by brianikim** [comment]
Closing this PR as we saw that the test failure is locally reproducible.

**Pull request closed without merging**
