### PR TITLE
COMMERCE-11847, COMMERCE-11848

### PR DESCRIPTION
**Pull request by victorcdp**
Related Issues: [COMMERCE-11847](https://liferay.atlassian.net/browse/COMMERCE-11847), [COMMERCE-11848](https://liferay.atlassian.net/browse/COMMERCE-11848)

### CODE REVIEW

**Comment by victorcdp** [comment]
ci:test:sf

**Comment by brianikim** [comment]
Looks fine. forward to liferay-commerce. Thanks.

**Comment by brianikim** [comment]
Actually do not forward yet

**Comment by brianikim** [comment]
Only forward COMMERCE-11847. Thanks.

**Pull request closed without merging**
