### PR TITLE
COMMERCE-9793 - Space added between quantity and 'In Stock'

### PR DESCRIPTION
**Pull request by elocamp**
The problem was caused because there wasn't a space between the functions to return the quantity in stock and to get the language key for 'In Stock'.
The proposed fix is just to add this missing space between the functions.

Related ticket: https://issues.liferay.com/browse/COMMERCE-9793

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
https://github.com/liferay-commerce/liferay-portal/pull/3272

**Comment by elocamp** [comment]
ci:reopen

**Comment by elocamp** [comment]
ci:test:sf

**Pull request closed without merging**
