### PR TITLE
[TS] LPS-103347 Add Batch Engine to language keys

### PR DESCRIPTION
**Pull request by katienesterovich**
https://issues.liferay.com/browse/LPS-103347

Language.properties file was missing the language key for `category.batch-engine`

### CODE REVIEW

**Comment by katienesterovich** [comment]
ci:test:sf

**Comment by katienesterovich** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
https://github.com/SamZiemer/liferay-portal/pull/675

**Pull request closed without merging**
