### PR TITLE
LPS-101544 Translations for structures appear empty when default site…

### PR DESCRIPTION
**Pull request by matthewchan1**
… language is changed

https://issues.liferay.com/browse/LPS-101544

Issue:
Changing a site's default locale in site configurations, then limiting available locales to just that language is defaulting to blank text for custom web content fields.

The main problem is that neither the current nor default translations are present in availableLocales. In this case, since there is just one availableLocales value, it will be more user-friendly to display the existing localization rather than empty fields.

Fix:
Locale is passed in a chain of function calls in DDMFormFieldFreeMarkerRenderer.java, so changing the locale in render() at the highest level will fix problems with both field options and titles appearing blank. I just fetched the locale in availableLocales and set it as the default language. The result is that text appears in default as per its original definition in the Edit Structure page.

### CODE REVIEW

**Comment by matthewchan1** [comment]
ci:test:relevant

**Comment by matthewchan1** [comment]
ci:test:sf

**Comment by brianikim** [comment]
will be reviewed tomorrow.

**Comment by brianikim** [comment]
https://github.com/natocesarrego/liferay-portal/pull/167

**Pull request closed without merging**
