### PR TITLE
LPS-105538 Add bulk actions to Accounts Toolbar

### PR DESCRIPTION
**Pull request by katienesterovich**
https://issues.liferay.com/browse/LPS-105538

The functionality may have been left out intentionally, as the option is also missing from most toolbars in Control Panel (i.e Users and Organizations > Users, Users and Organizations > Organizations, User Groups, Roles, etc.)

Bulk Actions implemented in Accounts and Account Users 
image

image

### CODE REVIEW

**Comment by katienesterovich** [comment]
ci:test:sf

**Comment by katienesterovich** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @katienesterovich ,

Sanity check. When you click Clear or Delete while multiple items are selected, does the Clear and Delete functionality work as intended?

**Comment by katienesterovich** [comment]
Hey @brianikim, 
Yes they do - tested with 6 entries on a search container with delta=5.  
`Clear` clears the selection on all pages. 
`Select all` selects options on all pages.

**Comment by brianikim** [comment]
How about the deletion behavior? Does it delete all 6 entries after you select all->delete?

**Comment by katienesterovich** [comment]
Good catch - it only deletes the contents on the first page despite displaying "All selected". Let me see if I can get it to work.

**Comment by katienesterovich** [comment]
ci:stop

**Comment by brianikim** [comment]
All selected is for the first page Katie. That is the correct behavior. I will be rerunning ci:test

**Comment by brianikim** [comment]
ci:test:relevant

**Pull request closed without merging**
