### PR TITLE
LPS-102150 Typo in Analytics Administrator role description

### PR DESCRIPTION
**Pull request by katienesterovich**
https://issues.liferay.com/browse/LPS-102150

This is a workaround rather than a true fix. Role descriptions are defined in `portal.properties` and do not use language keys. Putting a comma segregates the sentence into an array of strings and any spaces after the comma are trimmed when put back together.

The descriptions of other roles exclude commas (for example, Site Administrator).

### CODE REVIEW

**Comment by katienesterovich** [comment]
ci:test:sf

**Comment by katienesterovich** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Will be sent up as soon as CI finishes with good results.

**Comment by brianikim** [comment]
https://github.com/SamZiemer/liferay-portal/pull/715

**Pull request closed without merging**
