### PR TITLE
LPS-121301 Fix the redirect for edit message

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-121301

The issue here was that the redirect was being overwritten by a newly generated URL.
To fix the issue, I deleted the code that is creating the URL and had getRedirect return the redirect from the actionRequest.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
See: https://github.com/SamZiemer/liferay-portal/pull/761

**Pull request closed without merging**
