### PR TITLE
LPS-107104 Missing language key when attempting to enter a category that does not exist

### PR DESCRIPTION
**Pull request by katienesterovich**
Solves [LPS-107104](https://issues.liferay.com/browse/LPS-107104
) and [LPS-107102](https://issues.liferay.com/browse/LPS-107102).

Caused by removal of soy templates in [LPS-100134](https://issues.liferay.com/browse/LPS-100134) 5848c49ce3585f29f97482ad6b24630f3778e43e and moving implementation to React in [LPS-100140](https://issues.liferay.com/browse/LPS-100140) 72cf6b4a0d0c16f101fb7f077465a5f53923a954.

### CODE REVIEW

**Comment by katienesterovich** [comment]
ci:test:sf

**Comment by katienesterovich** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
https://github.com/SamZiemer/liferay-portal/pull/717

**Comment by brianikim** [comment]
https://github.com/SamZiemer/liferay-portal/pull/717

**Pull request closed without merging**
