### PR TITLE
LPS-97585 Index expando field as keyword and make it case insensitive 

### PR DESCRIPTION
**Pull request by katienesterovich**
https://issues.liferay.com/browse/LPS-97585

https://github.com/brianikim/liferay-portal/pull/75 Verified that the fix works and ran source formatter.
Note: to verify, deploy and Reindex all searches indexes in Control Panel > Configuration > Search

### CODE REVIEW

**Comment by katienesterovich** [comment]
ci:test:sf

**Comment by katienesterovich** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
PR will be sent tomorrow.

**Comment by brianikim** [comment]
https://github.com/SamZiemer/liferay-portal/pull/695

**Pull request closed without merging**
