### PR TITLE
LPS-77054 SF. Simplify. No need to extend FileEntryDisplayContextHelper

### PR DESCRIPTION
**Pull request by sergiogonzalez**

### CODE REVIEW

**Comment by sergiogonzalez** [comment]
Hey @brianikim 
I simplify your fix and also did some changes but I couldn't test it. Can you please review and test my changes to see if they are ok? If so please let me know so I can forward the pull to Brian.
Thanks

cc/ @jonathanmccann

**Comment by sergiogonzalez** [comment]
ci:test

**Comment by brianikim** [comment]
Hello @sergiogonzalez ,

The changes look great!

Having FileShortcutDisplayContextHelper as its own class was what I originally intended as well so the changes there are all what I expected them to be. 

Thank you for simplifying the logic in UIItemsBuilder; everything in there also looks great. I will definitely study your changes, so in the future, I will be able to provide cleaner fixes.

I have tested your changes in the bundle, and it does not produce any problems and seems to pass all the edge cases that I have found.

I do not have CI:Test set up, so I am not sure if that will run. However, from my testing, the changes perform their intended effects and do not produce any new problems.

Please let me know if you need anything else. Thanks.

**Comment by brianikim** [comment]
Hello @sergiogonzalez,

Please let me know if you wanted me to request another PR to you with the fixed changes.

Sincerely,
Brian Kim

**Comment by sergiogonzalez** [comment]
Hey @brianikim I just forwarded the pull to Brian. Thank for testing it.
https://github.com/brianchandotcom/liferay-portal/pull/55326

**Pull request closed without merging**
