### PR TITLE
LPS-119216 Add web content author info to edit workflow task

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-119216

Author of web content was removed from the edit workflow task page in [LPS-61400](https://issues.liferay.com/browse/LPS-61400).
I added the info back and changed the tag from `<liferay-ui:asset-metadata>` to `<liferay-asset:asset-metadata>`

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by noornajj** [comment]
ci:test:sf

**Comment by brianikim** [comment]
https://github.com/jonathanmccann/liferay-portal/pull/1848

**Pull request closed without merging**
