### PR TITLE
LPS-105745 Change btn.secondary background to match atlas theme

### PR DESCRIPTION
**Pull request by katienesterovich**
https://issues.liferay.com/browse/LPS-105745

Generated Theme
image

Default Theme
image

Changed the btn.secondary color to white - matching the atlas theme. 
Can't change the text color - will affect default theme.

### CODE REVIEW

**Comment by katienesterovich** [comment]
ci:test:formatSource

**Comment by katienesterovich** [comment]
ci:stop

**Comment by katienesterovich** [comment]
ci:test:sf

**Comment by katienesterovich** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Review has completed. I will be sending it up once test completes.

**Comment by brianikim** [comment]
https://github.com/SamZiemer/liferay-portal/pull/704

**Pull request closed without merging**
