### PR TITLE
LPS-118136 Fixing model validator to correctly handle exception errors for featured image

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-118136

The issues here were the following:
1. When the image is deleted and modelValidate creates a temp file for the image, it tries to write out smallImageBytes but this is a null value. This results in a file exception error to occur and the model validator does not catch this exception. I fixed this by adding a condition before creating the temp file that smallImageBytes not be equal to null and also adding a check whether smallImageBytes is null in validateReferences() before throwing a NoSuchImageException.
2. The script was not sending descriptive exception error messages. I added two messages; one in validateReferences() for when the image does not exist, and one in validate() for when the file extension is not valid.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
reviewing now

**Comment by brianikim** [comment]
Closing as it is dependent on LPS-118134. Resend with both PRs consolidated.

**Pull request closed without merging**
