### PR TITLE
[TS] LPS-103270 Add negative number validation for asset tag configuration

### PR DESCRIPTION
**Pull request by katienesterovich**
https://issues.liferay.com/browse/LPS-103270

Added a check to throw "Maximum number of tags cannot be negative" error if input value is negative for System and Company Asset Tag configurations. 

Behavior: value resets back to previous number. 

Screen Shot 2019-10-21 at 12 02 27 PM

### CODE REVIEW

**Comment by katienesterovich** [comment]
ci:test:sf

**Comment by katienesterovich** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Reviewing now :)

**Comment by brianikim** [comment]
See: https://github.com/SamZiemer/liferay-portal/pull/677

**Pull request closed without merging**
