### PR TITLE
LPS-105081 The eye icon does not appear in gray under list view when the cursor moves over it

### PR DESCRIPTION
**Pull request by katienesterovich**
https://issues.liferay.com/browse/LPS-105081

Changed the icon to 'Clay', to match `Table` eye icon (see https://github.com/liferay/liferay-portal/commit/3d1abab451c177e69881696808e1227e051f1501#diff-0fc0f7561cfce04f47d0417e2f7b6948R201).

### CODE REVIEW

**Comment by katienesterovich** [comment]
ci:test:sf

**Comment by katienesterovich** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:stop

**Comment by brianikim** [comment]
https://github.com/SamZiemer/liferay-portal/pull/703

**Pull request closed without merging**
